tags:
  name: Produto
  description: Endpoints da entidade Produto

paths:
  /produto:
    get:
      summary: Retorna todos os produtos cadastrados
      tags: [Produto]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Produto"
    post:
      summary: Cria um novo produto
      tags: [Produto]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateProdutoDto"
        required: true
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Produto"
        "400":
          description: Produto já existe.
          content:
            application/json:
              schema:
                type: object
                example: { msg: "Produto já existe" }
        "403":
          description: Operação não autorizada.
          content:
            application/json:
              schema:
                type: object
                example: { msg: "Operação não autorizada" }

  /produto/{id}:
    get:
      summary: Retorna os dados de um produto
      tags: [Produto]
      parameters:
        - name: id
          in: path
          description: ID do produto (UUID)
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Produto"
        "400":
          description: Produto não existe.
          content:
            application/json:
              schema:
                type: object
                example: { msg: "Produto não existe" }

    put:
      summary: Modifica os dados de um dado produto
      tags: [Produto]
      parameters:
        - name: id
          in: path
          description: ID do produto (UUID)
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateProdutoDto"
        required: true
      responses:
        "200":
          description: Produto atualizado.
          content:
            application/json:
              schema:
                type: object
                example: { msg: "Produto atualizado." }
        "400":
          description: O produto não existe.
          content:
            application/json:
              schema:
                type: object
                example: { msg: "Produto não existe." }
    delete:
      summary: Apaga um produto cadastrado.
      tags: [Produto]
      parameters:
        - name: id
          in: path
          description: ID do produto (UUID)
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Produto apagado.
          content:
            application/json:
              schema:
                type: object
                example: { msg: "Produto apagado." }
        "400":
          description: O produto não existe.
          content:
            application/json:
              schema:
                type: object
                example: { msg: "Produto não existe." }


components:
  schemas:
    Produto:
      type: object
      properties:
        id:
          type: string
          description: ID do produto no formato UUID.
          example: a0debc32-0184-4a9c-b216-5428b6f536d4
        nome:
          type: string
          description: Nome do produto.
          example: Celular Motorola Moto G10
        preco:
          type: float
          description: Preço.
          example: 1299.99
        estoque:
          type: integer
          description: Número de itens no estoque.
          example: 100
        createdAt:
          type: date
          description: Data de criação do item no banco de dados.
          example: '2022-12-31T23:59:59Z'
        updatedAt:
          type: date
          description: Data de atualização do item no banco de dados.
          example: '2023-01-01T12:00:00Z'
    CreateProdutoDto:
      type: object
      properties:
        nome:
          type: string
          description: Nome do produto.
          example: Celular Samsung Galaxy S21
        preco:
          type: float
          description: Preço.
          example: 2499.99
        estoque:
          type: integer
          description: Número de itens no estoque.
          example: 50
    UpdateProdutoDto:
      type: object
      properties:
        nome:
          type: string
          description: Nome do produto.
          example: Notebook Dell Inspiron 15
        preco:
          type: float
          description: Preço.
          example: 3499.99
        estoque:
          type: integer
          description: Número de itens no estoque.
          example: 20
